version: '3.3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/src/staticfiles:/staticfiles
      - ./backend/src/media:/media

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/backend.env
    volumes:
      - ./backend/src/staticfiles:/usr/src/app/staticfiles
      - ./backend/src/media:/usr/src/app/media
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - ./postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
